# Generated by Django 2.2 on 2022-01-16 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('time_created', models.DateField(auto_now_add=True)),
                ('publisher', models.CharField(max_length=100)),
                ('heading', models.CharField(max_length=100)),
                ('content', models.TextField()),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
    ]
